apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: manahil20i2302/mlops_assignment2_20i-2302-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets  # Name of the secret
                  key: MONGO_URI         # Key for the Mongo URI
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets  # Name of the secret
                  key: MAIL_USERNAME      # Key for the mail username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets  # Name of the secret
                  key: MAIL_PASSWORD      # Key for the mail password
